### ISSUE TITLE
CAD Access

### ISSUE THREAD

**Issue by brianvoe** [leddhedd/BreakNeck#12]
I love the idea and want to try it out but wanted to try a couple of alternative changes. Any chance you can share the CAD files?

**Comment by leddhedd** [comment]
Breakneck is getting a bit of an overhaul, hence the slow progress updates, but once that is released, which should be pretty soon, there will be CAD avaliable for people to mess around with there :)

**Comment by brianvoe** [comment]
ok cool thanks for the update!
