### ISSUE TITLE
Beacon Normal orientation support

### ISSUE THREAD

**Issue by thiagolocatelli** [leddhedd/BreakNeck#2]
The current beacon mount does not have enough clearance for the beacon pcb.

![1E2B23A2-30D2-4B89-8DE2-66CD6D2D7F04](https://user-images.githubusercontent.com/1017031/232476966-aea7e77a-e2ba-4113-85d4-0ada1a54b49d.jpg)

**Comment by leddhedd** [comment]
Clearance for the standard beacon orientation will be a problem on all 3 mounts, will make adjustments to allow for either to be used
