### ISSUE TITLE
MGN12H Rail mount incompatible with beacon mount

### ISSUE THREAD

**Issue by RefractingPrism** [leddhedd/BreakNeck#9]
The MGN12H mount is incompatible with the small duct beacon mount. The mgn12h rail mount is missing the triangular cutout for proper fitment.

**Comment by leddhedd** [comment]
sorry yes, ill update that part now, however it important to note that the small beacon mount cannot be used with the carraige clamping screws that go through the carriage piece

**Comment by RefractingPrism** [comment]
just to clarify this was the section of the probe mount that conflicts with the carriage mount. 
![probe conflict](https://github.com/leddhedd/BreakNeck/assets/126586937/a95123b1-5747-4fc1-ab5e-5152e4783be5)

I guess im having trouble following which screws make it not compatible.

**Comment by leddhedd** [comment]
yes sorry, that just needs entirely removing, just pointing out that the two holes in the front of the carraige there below the rail mounting screws need to be empty, if you put the heatsets in there, they are technically in the beacon exclusion zone

im just updating that part now, should be on the repo in a few minutes

**Comment by leddhedd** [comment]
![image](https://github.com/leddhedd/BreakNeck/assets/26231032/4c038aa5-58ac-4b8f-869a-ed220b063a8b)
these two holes here, im uploading the updated beacon probe mounts, as well as updated probe mounts for everything that should all now be compatible with the new carriages, apologies for the inconvinience on that one

**Comment by RefractingPrism** [comment]
Thanks for following up, i didnt think of the exclusion zone but that makes sense now!
